export { IMember, IRawUser };

declare global {
  interface IMember {
    id: string;
    firstname?: string;
    lastname?: string;
    title?: string;
    password?: string | null;
    temporaryPassword?: boolean;
    fullName?: string;
    slug?: string;
    arisEmail?: string;
    contactEmail?: string;
    discordName?: string;
    rsiHandle?: string;
    potrait?: string;
    pronom?: 'Sie' | 'Er';
    sex?: 'male' | 'female';
    roles?: string[];
    position?: { id: string; position: string; permissionLevel: number };
    admin?: boolean;
    headOfDepartment?: boolean;
    department?: IDepartment;
    birthplace?: ILandingZone;
    birthdate?: string;
    currentplace?: ILandingZone;
    ueeState?: 'citizen' | 'civilian';
    citizenReason?: 'Militärischer Dienst' | 'Besondere Bildung' | 'Soziales Engagement' | null;
    dutyState?: boolean;
    duty?: {
      period: string;
      end: string;
      division: string;
      divisionValue: string;
    };
    educationState?: boolean;
    education?: {
      name: string;
      period: string;
      place: string;
    };
    haircolor?: string;
    eyecolor?: string;
    height?: number;
    weight?: number;
    hobbies?: string;
    habits?: string;
    talents?: string;
    tics?: string;
    activities?: string;
    mysterious?: string;
    character?: string;
    fears?: string;
    books?: string;
    music?: string;
    movies?: string;
    colors?: string;
    clothing?: string;
    food?: string;
    drink?: string;
    alcohol?: string;
    loves?: string;
    hates?: string;
    medicalinfo?: string;
    biography?: string;
    hangarLink?: string;
    biographyLink?: string;
    biographyAmsLink?: string;
    hangar?: IHangarItem[];
  }

  interface IRawUser {
    id: string;
    first_name?: string;
    last_name?: string;
    email?: string;
    password?: string | null;
    location?: string;
    title?: string | null;
    description?: string | null;
    tags?: string;
    avatar?: string;
    language?: string;
    tfa_secret?: string | null;
    status?: string;
    role?: string;
    token?: string;
    last_access?: string;
    last_page?: string;
    provider?: string;
    external_identifier?: string | null;
    auth_data?: string | null;
    email_notifications?: boolean;
    appearance?: string;
    theme_dark?: string | null;
    theme_light?: string | null;
    theme_light_overrides?: string | null;
    theme_dark_overrides?: string | null;
    contactEmail?: string;
    discordName?: string;
    rsiHandle?: string;
    slug?: string;
    temporaryPassword?: boolean;
    sex?: 'male' | 'female';
    roles?: string[];
    head_of_department?: boolean;
    birthdate?: string | null;
    birthplace?: IRawLandingZone;
    citizen?: boolean;
    citizenReason?: string | null;
    dutyPeriod?: string | null;
    dutyEnd?: string | null;
    study?: string | null;
    studyPeriod?: string | null;
    studyPlace?: string | null;
    haircolor?: string | null;
    eyecolor?: string | null;
    height?: string | null;
    weight?: string | null;
    currentResidence?: IRawLandingZone;
    habits?: string | null;
    talents?: string | null;
    tics?: string | null;
    activities?: string | null;
    mysteriousThings?: string | null;
    characterTrait?: string | null;
    fears?: string | null;
    books?: string | null;
    music?: string | null;
    movies?: string | null;
    colors?: string | null;
    clothing?: string | null;
    food?: string | null;
    drink?: string | null;
    alcohol?: string | null;
    loves?: string | null;
    hates?: string | null;
    medicalInformations?: string | null;
    biography?: string;
    dutyState?: boolean;
    educationState?: boolean;
    hobbies?: string | null;
  }
}
