export { Ship }

declare global {
  interface Ship {
    id: String
    erkulId: String
    smId: String
    flId: String
    scId: String
    apiId: String
    rsiId: String
    name: String
    p4kName: String
    rsiName: String
    slug: String
    flSlug: String
    rsiSlug: String
    p4kMode: String
    p4kId: String
    p4kVersion: String
    manufacturer: Company
    storePage: String
    salesPage: String
    length: number
    beam: number
    height: number
    mass: number
    cargo: number
    price: number
    pledgePrice: number
    onSale: Boolean
    productionStatus: String
    readyPatch: String
    career: String
    hydrogenTank: number
    quantumTank: number
    minCrew: number
    maxCrew: number
    scmSpeed: number
    maxSpeed: number
    maxGroundSpeed: number
    zeroToScm: number
    zeroToMax: number
    scmToZero: number
    maxToZero: number
    pitchMax: number
    yawMax: number
    rollMax: number
    xaxisAcceleration: String
    yaxisAcceleration: String
    zaxisAcceleration: String
    brochure: String
    holo: String
    holoColored: Boolean
    hardpoints: Array
    weaponHardpoints: Array
    variants: Array
    loaners: Array
    paints: String
    classification: String
    focus: String
    lastUpdatedAt: String
    insuranceClaimTime: number
    insuranceExpeditedClaimTime: number
    insuranceExpeditedCost: number
    storeImage: String
    gallery: Array<String>
    commercialVideoId: String
    tags: Array<String>
    groundVehicle: Boolean
    role: String
    description: String
    history: String
    rating: ShipRating
    size: number
    sortSize: number
    modules: Array<ShipModule>
  }
}
